esphome:
  name: !secret model_name
  includes:
    - citilux_ir.h

bk72xx:
  board: cb3s

logger:
  level: INFO

api:
  reboot_timeout: 1min
  services:
    - service: ir_send
      variables:
        data: string
        repeat_times: int
      then:
        - script.execute: 
            id: send_pronto
            repeat_count: !lambda |-
              return repeat_times ? repeat_times : 1;
            ir_code: !lambda return data;

script:
  - id: send_pronto
    mode: queued
    parameters:
      ir_code: string
      repeat_count: int
    then:
      - repeat:
          count: !lambda return repeat_count;
          then:
            - delay: 150ms
            - remote_transmitter.transmit_pronto:
                data: !lambda return ir_code;

wifi:
  ssid: !secret ssid
  password: !secret password
  fast_connect: true
  manual_ip:
    static_ip: !secret ip
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  ap:
    password: !secret password

ota:
  - platform: esphome
    password: !secret password

web_server:
  port: 80
  local: True
  version: 2
  # auth:
  #   username: !secret username
  #   password: !secret password

time:
  - platform: homeassistant
    id: ha_time

remote_transmitter:
  id: transmitter
  carrier_duty_percent: 50%
  pin:
    number: P26
    inverted: false

button:
  - platform: factory_reset
    id: factory_reset_trigger
    name: "Сбросить настройки"

remote_receiver:
  id: rcvr
  pin:
    number: P7
    inverted: true
    mode:
      input: true
      pullup: true
  dump:
  - pronto

binary_sensor:
  - platform: gpio
    id: bottom_button
    pin:
      number: P6
      inverted: true
    filters:
      - delayed_on: 5s
    on_press:
      - output.turn_on:  onboard_led
      - button.press: factory_reset_trigger
    on_release:
      - output.turn_off: onboard_led

output:
  - id: onboard_led
    platform: gpio
    pin:
      number: P8
    inverted: false

climate:
  - platform: coolix
    sensor: current_temperature
    name: Electrolux EACS-07HAR_A/N3_21Y
    # receiver_id: rcvr

sensor:
  - platform: homeassistant
    id: current_temperature
    entity_id: sensor.atc_6a6e_temperature
    internal: true

light:
  - platform: custom
    lambda: |-
      auto citilux_ir = new CitiluxIROutput();
      App.register_component(citilux_ir);
      return {citilux_ir};
    lights:
      - name: "Люстра"